use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

def common_pods
  pod 'MSMobAdSDK/MS','2.5.1.2'
  pod 'BaiduMobAdSDK', '5.370'
  pod 'Ads-CN-Beta', '6.5.0.5', :subspecs => ['BUAdSDK', 'CSJMediation']
  pod 'JADYun','2.6.4'
  pod 'JADYunMotion','2.6.4'
  pod 'KSAdSDK','3.3.71'
  pod 'GDTMobSDK','4.15.10'
  pod 'SigmobAd-iOS','4.11.1'
  pod 'WechatOpenSDK', '~> 1.8.6'
  pod 'MSMTACustomAdapter', :path => '../../MSMTACustomAdapter.podspec'
  # pod 'MentaUnifiedSDK',    :path => '/Users/jdy/Desktop/Menta-iOS/MentaUnifiedSDK.podspec'
  # pod 'MentaVlionBaseSDK',  :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionBaseSDK.podspec'
  # pod 'MentaVlionSDK',      :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionSDK.podspec'
  # pod 'MentaVlionAdapter',  :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionAdapter.podspec'
  # pod 'MentaKSAdapter',     :path => '/Users/jdy/Desktop/Menta-iOS/MentaKSAdapter.podspec'
  # pod 'MentaIFLYAdapter',   :path => '/Users/jdy/Desktop/Menta-iOS/MentaIFLYAdapter.podspec'
end

target 'MSAdSDK_Example' do
  common_pods
  pod 'Masonry'
  pod 'SDWebImage','5.8.4'
  pod 'IQKeyboardManager'
end

target 'MSAdSDK-Example-Swift' do
  common_pods
  pod 'SnapKit', '~> 5.6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
         end
    end
  end
end
